name: py-js
options:
  bundleIdPrefix: org.me
settings:
  CODE_SIGN_IDENTITY: "-"
  DEVELOPMENT_TEAM: ""
  GCC_OPTIMIZATION_LEVEL: 0
  GCC_NO_COMMON_BLOCKS: No
  HEADER_SEARCH_PATHS:
    - $(C74SUPPORT)/max-includes
    - $(C74SUPPORT)/msp-includes
    - $(C74SUPPORT)/jit-includes
    - $(PROJECT_HEADERS)
  INFOPLIST_FILE: $(SRCROOT)/../../../Info.plist
  LIBRARY_SEARCH_PATHS: $(PROJECT_LIBS)
  OTHER_LDFLAGS:
    - $(C74_SYM_LINKER_FLAGS)
    - $(MSP_JIT_LDFLAGS)
    - $(PROJECT_LDFLAGS)
  PRODUCT_NAME: $(TARGET_NAME)
configFiles:
  Debug: project.xcconfig
  Release: project.xcconfig

targets:
  py:
    type: bundle
    platform: macOS
    sources:
      - ../../py.c
      - ../../api.c
      - path: ../build/lib/python-static/lib/python311.zip
        buildPhase:
          copyFiles:
            destination: resources
            subpath: lib
      - path: ../build/lib/python-static/lib/python3.11
        type: folder
        buildPhase:
          copyFiles:
            destination: resources
            subpath: lib
    dependencies:
      - sdk: CoreFoundation.framework
    settings:
      MACOSX_DEPLOYMENT_TARGET: "10.13"

  pyjs:
    type: bundle
    platform: macOS
    sources:
      - ../../pyjs.c
      - path: ../build/lib/python-static/lib/python311.zip
        buildPhase:
          copyFiles:
            destination: resources
            subpath: lib
      - path: ../build/lib/python-static/lib/python3.11
        type: folder
        buildPhase:
          copyFiles:
            destination: resources
            subpath: lib
    dependencies:
      - sdk: CoreFoundation.framework
    settings:
      MACOSX_DEPLOYMENT_TARGET: "10.13"
