static char* PY_DEFAULT_MODULE =
"import os\n"
"import subprocess\n"
"import shlex\n"
"\n"
"# ---------------------------------------------------------\n"
"# global constants\n"
"\n"
"EDITOR = 'Sublime Text' # can be changed of course\n"
"\n"
"\n"
"# ---------------------------------------------------------\n"
"# misc funcs\n"
"\n"
"def edit(path):\n"
"    editor = os.getenv('EDITOR', EDITOR)\n"
"    path = os.path.expanduser(path)\n"
"    shell(f'open -a \"{editor}\" \"{path}\"')\n"
"\n"
"\n"
"\n"
"# ---------------------------------------------------------\n"
"# funcs are used by methods\n"
"\n"
"def shell(cmd, err_func=None):\n"
"    result = None\n"
"    try:\n"
"        elems = shlex.split(cmd)\n"
"        elems[-1] = os.path.expanduser(elems[-1]) # ~/a/b.c -> /Users/xx/a/b.c\n"
"        result = subprocess.check_output(\n"
"            elems, encoding='utf8').strip()\n"
"    except subprocess.CalledProcessError as e:\n"
"        if err_func:\n"
"            err_func(e.stderr)\n"
"    except FileNotFoundError as e:\n"
"        if err_func:\n"
"            err_func(e.strerror)\n"
"    if result:\n"
"        return result\n"
"\n"
"\n"
"def out_dict(py_dict):\n"
"    res = []\n"
"    for k,v in py_dict.items():\n"
"        res.append(k)\n"
"        res.append(':')\n"
"        if type(v) in [list, set, tuple]:\n"
"            for i in v:\n"
"                res.append(i)\n"
"        else:\n"
"            res.append(v)\n"
"    return res\n"
"\n"
"def pipe(arg):\n"
"    args = arg.split()\n"
"    val = eval(args[0], locals(), globals())\n"
"    funcs = [eval(f, locals(), globals()) for f in args[1:]]\n"
"    for f in funcs:\n"
"        val = f(val)\n"
"    return val\n"
"\n"
"\n";
