project:
  type: book

book:
  title: "Python3 Externals for Max/MSP"
  subtitle: "A PyJS Project Guide"
  author: "S. Alireza"
  date: "7/19/2024"
  abstract: "Exploring different ways one can use Python3 in Max/MSP"
  url: "https://github.com/shakfu/py-js"
  version: "0.0.1"
  chapters:
    - index.qmd
    - part: "The Project"
      chapters:
        - src/overview.qmd
        - src/faq.qmd
        #- src/references.qmd

    - part: "Core Externals"
      chapters:
        - src/externals/py.qmd
        - src/externals/pyjs.qmd

    - part: "Experimental Externals"
      chapters:
        - src/externals/krait.qmd
        - src/externals/mamba.qmd
        - src/externals/cobra.qmd
        - src/externals/mxpy.qmd

    - part: "Alternative Externals"
      chapters:
        - src/externals/mpy.qmd
        - src/externals/pktpy.qmd
        - src/externals/pktpy2.qmd

    - part: "Networking Externals"
      chapters:
        - src/externals/zedit.qmd
        - src/externals/zpy.qmd
        - src/externals/zthread.qmd
        - src/externals/jmx.qmd

    # - part: "Builder"
    #   chapters:
    #     - src/builder/overview.qmd
    #     - src/builder/building-on-apple-silicon.qmd
    #     - src/builder/building-pyext-flext.qmd
    #     - src/builder/cmake.qmd
    #     - src/builder/codesign-notarize.qmd
    #     - src/builder/fix_arm64_bug.qmd
    #     - src/builder/github-actions.qmd
    #     - src/builder/make-dmg.qmd
    #     - src/builder/mappings.qmd
    #     - src/builder/packaging.qmd
    #     - src/builder/relocatable-python.qmd
    #     - src/builder/remove-detritus.qmd
    #     - src/builder/switching-between-modes.qmd
    #     - src/builder/xcconfig.qmd
    #     - src/builder/xcode-concepts.qmd
      
    # - part: "Development Guide"
    #   chapters:
    #     - src/dev/devguide.qmd
    #     - src/dev/py/bugs.qmd
    #     - src/dev/py/cython.qmd
    #     - src/dev/py/design.qmd
    #     - src/dev/py/dont.qmd
    #     - src/dev/py/editor.qmd
    #     - src/dev/py/buffer.qmd
    #     - src/dev/py/buffer-protocol.qmd
    #     - src/dev/py/escape_text.qmd
    #     - src/dev/py/experiments.qmd
    #     - src/dev/py/max-c-api.qmd
    #     - src/dev/py/max-fileformats.qmd
    #     - src/dev/py/numpy-error.qmd
    #     - src/dev/py/python-c-api.qmd
    #     - src/dev/py/python-shell-via-nodejs.qmd
    #     - src/dev/py/repl.qmd
    #     - src/dev/py/scripting-tips.qmd
    #     - src/dev/py/shared-python-problem.qmd
    #     - src/dev/py/snippets.qmd
    #     - src/dev/py/threading.qmd
    #     - src/dev/py/type-translation.qmd
    #     - src/dev/py/types.qmd
    #     - src/dev/pyjs/javascript.qmd
  appendices:
    - src/dev/devguide.qmd


bibliography: src/references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    mainfont: Palatino
    sansfont: Palatino
    # mainfont: Times New Roman
    # sansfont: Times New Roman
    # mainfont: Optima
    # sansfont: Optima

    monofont: inconsolata

    toc-title: Table of Contents
    toc-depth: 2
    lof: true
    lot: true
    number-sections: true
    number-depth: 1
    highlight-style: arrow

