name: build-windows
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: build with make
      run: make core-windows-pkg

    - name: cleanup
      run: cmake -P source/scripts/cmake/win_pkg_cleanup.cmake

    - name: pre-upload
      run: |
        mv source/docs/_book/Python3-Externals-for-Max-MSP.pdf ./userguide.pdf

    - uses: actions/upload-artifact@v4
      with:
        name: pyjs-core-win64-externals
        path: |
            docs/py.maxref.xml
            docs/pyjs.maxref.xml
            externals
            help/py.maxhelp
            help/pyjs.maxhelp
            examples
            javascript
            jsextensions
            patchers
            LICENSE
            README.md
            userguide.pdf
            support
